---
name: library
bundle_prefix:
  - ycappuccino.storage
  - ycappuccino.endpoints_storage
  - ycappuccino.http_server
  - library
layers:
  ycappuccino_storage_memory:
    active: true
config:
  http_server:
    active: true
    port: 9000
    ip: localhost
